export default {name: 'Currency', icons: [
  "bitcoin (alias)",
  "btc",
  "cny (alias)",
  "dollar (alias)",
  "eur",
  "euro (alias)",
  "gbp",
  "gg",
  "gg-circle",
  "ils",
  "inr",
  "jpy",
  "krw",
  "money",
  "rmb (alias)",
  "rouble (alias)",
  "rub",
  "ruble (alias)",
  "rupee (alias)",
  "shekel (alias)",
  "sheqel (alias)",
  "try",
  "turkish-lira (alias)",
  "usd",
  "viacoin",
  "won (alias)",
  "yen (alias)",
]}
