export default {name: 'File Type', icons: [
  "file",
  "file-archive-o",
  "file-audio-o",
  "file-code-o",
  "file-excel-o",
  "file-image-o",
  "file-movie-o (alias)",
  "file-o",
  "file-pdf-o",
  "file-photo-o (alias)",
  "file-picture-o (alias)",
  "file-powerpoint-o",
  "file-sound-o (alias)",
  "file-text",
  "file-text-o",
  "file-video-o",
  "file-word-o",
  "file-zip-o (alias)",
]}